name: cicd

on:
  push:
    branches: [ main ]
    paths-ignore:
      - .gitignore
      - CODE_OF_CONDUCT.md
      - LICENSE
      - README.md

permissions:
  id-token: write
  contents: read

jobs:

  build:
    uses: ./.github/workflows/build.yml
    with:
      build-artifacts: true